site:
  title: ARC42 Software Architecture Documentation Template
  start_page: doc:ROOT:01_introduction_and_goals.adoc
  url: https://drehtuer.github.io/antora/

output:
  clean: true
  dir: build

runtime:
  cache_dir: ./.cache/antora
  log:
    level: info

content:
  sources:
    - url: https://github.com/drehtuer/antora.git
      start_path: doc

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

asciidoc:
  sourcemap: true
  extensions:
    - asciidoctor-jira
    - asciidoctor-kroki
    - asciidoctor-treeview
  attributes:
    icons: font
    icontype: svg
    lang: en
    page-pagination: ""
