site:
  title: ARC42 Software Architecture Documentation Template
  start_page: architecture:ROOT:index.adoc
content:
  sources:
    - url: https://github.com/drehtuer/antora.git
      start_path: doc
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
asciidoc:
  sourcemap: true
output:
  clean: true
